### ISSUE TITLE
Date sort options for builds

### ISSUE THREAD

**Issue by csdepop100** [Sendouc/sendou.ink#1443] opened 2023-08-02 13:49 UTC
Hi all,
I wanted to look up how builds might've changed with the new patch. For that it'd be extremely helpful if there was an option to sort builds by date (or maybe also how many AP ability XY has). 
I haven't worked on frontend-stuff yet, but I'd be happy to work on this feature to acquire that new skill 😁 
![image](https://github.com/Sendouc/sendou.ink/assets/49524272/de352ac6-b7c8-4704-92c0-d5aefa6d665b)

**Comment by Sendouc** [comment] 2023-08-02 20:08
Hey! Just to clarify a few things:

Re: updated at, actually the builds are sorted in that order already. It just shows plus server members first but that's intentional as average user build is bit of a hit or miss honestly.

> maybe also how many AP ability XY has

Isn't that just the existing "Add filter" functionality?

You are not the only one ask about this btw so maybe it is some kind of UI issue but just trying to understand your PoV first.

**Comment by csdepop100** [comment] 2023-08-02 21:38
Ah I see, yes that makes sense, and I agree. Now that I have this information the sorting is quite clear. 
I think it would be great to clarify that in the UI. For example: that sort-button with "By Date (+ first)" as default or by making the plus-marker a bit more visible with a different colour or so? But having options is always great imo
> Isn't that just the existing "Add filter" functionality?
Kind of, but also not quite. Sometimes I wanna look at sets with different amounts of swim speed up for example and then look how the builds change with inc/dec ssu and see the trade-offs without adjusting the filter everytime. That would be just a quality of life thing, that should be almost no effort once there is a sort-functionality anyways. 
Thanks for the clarification tho!

**Comment by Sendouc** [comment] 2023-08-06 07:19
Regarding the date filtering got someone else asking for something similar:

<img width="383" alt="image" src="https://github.com/Sendouc/sendou.ink/assets/38327916/b0898a3f-da27-444c-9734-b3dc346baf65">

I could see value in it, just need to think how exactly to do it for a good UX. I'd give a few default options (e.g. "last 30 days", "this patch", "this year") and then a custom option as well. But it's something worth considering for sure. For other filters I'd discuss those separately but maybe this would be first to be implemented.

**Comment by csdepop100** [comment] 2023-08-11 09:35
I'd say this is a very helpful way. It would definitely solve the difficulties I faced and be more in line withthe overall ux.

**Comment by Sendouc** [comment] 2023-12-30 22:30
Duplicate of https://github.com/Sendouc/sendou.ink/issues/1486

**Closed by Sendouc** 2023-12-30 22:30 UTC
