### ISSUE TITLE
Ink Vacs sucking radius graph is unusable

### ISSUE THREAD

**Issue by Phil-hacker** [Sendouc/sendou.ink#1837] opened 2024-08-18 15:57 UTC
ink vacs sucking radius graph is unusable
![grafik](https://github.com/user-attachments/assets/0583a879-712b-42e7-83c3-f5c4f0846a86)
splitting the radius into min and max radius would probably solve this issue

**Comment by ximk** [comment] 2024-08-18 15:58
Duplicate of #1820

**Closed** 2024-08-19 17:35 UTC
