### ISSUE TITLE
Select badge that is by default big when opening user profile

### ISSUE THREAD

**Issue by Sendouc** [Sendouc/sendou.ink#1031] opened 2022-10-21 18:25 UTC
Currently user can't choose which badge is shown as big by default:

<img width="449" alt="image" src="https://user-images.githubusercontent.com/38327916/197263794-fa3aaa79-6707-4623-a21f-04ab38491061.png">

There might be a badge they are particularly proud of so on the edit profile page could have a dropdown of badges user has and the selected one is shown first.

**Comment by remmycat** [comment] 2022-10-21 18:51
I think this might be a duplicate of #839?

**Comment by Sendouc** [comment] 2022-10-21 18:53
Yes it is :)

**Closed** 2022-10-21 18:53 UTC
Labels: help wanted, user page
